### ISSUE TITLE
Could not find block with ID

### ISSUE THREAD

**Issue by xzavrel** [kromiii/notion-to-slides#10]
Hi, I'm trying the tool but I always get `Could not find block with ID` error. I have made the integration and exported the token. The page is very simple, no linked objects.

```
pageId: 135e58a77a3e80dab8b5ccf48d077917
Example app listening at http://localhost:8080
@notionhq/client warn: request fail {
  code: 'object_not_found',
  message: 'Could not find block with ID: 135e58a7-7a3e-80da-b8b5-ccf48d077917. Make sure the relevant pages and databases are shared with your integration.'
}
/home/xzavrel/Developer.git/thirdparty/notion-to-slides/node_modules/@notionhq/client/build/src/errors.js:162
        return new APIResponseError({
               ^

APIResponseError: Could not find block with ID: 135e58a7-7a3e-80da-b8b5-ccf48d077917. Make sure the relevant pages and databases are shared with your integration.
    at buildRequestError (/home/xzavrel/Developer.git/thirdparty/notion-to-slides/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/home/xzavrel/Developer.git/thirdparty/notion-to-slides/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getBlockChildren (/home/xzavrel/Developer.git/thirdparty/notion-to-slides/node_modules/notion-to-md/build/utils/notion.js:9:27)
    at async NotionToMarkdown.pageToMarkdown (/home/xzavrel/Developer.git/thirdparty/notion-to-slides/node_modules/notion-to-md/build/notion-to-md.js:137:24) {
  code: 'object_not_found',
  status: 404,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Tue, 05 Nov 2024 22:00:41 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'transfer-encoding': [ 'chunked' ],
      connection: [ 'close' ],
      'cf-ray': [ '8de01e3b2aaa2794-PRG' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      etag: [ 'W/"10a-wCHhxUfGFXPFi07OObRvJizqflw"' ],
      'strict-transport-security': [ 'max-age=31536000; includeSubDomains; preload' ],
      vary: [ 'Accept-Encoding' ],
      'content-security-policy': [ "default-src 'none'" ],
      'referrer-policy': [ 'strict-origin-when-cross-origin' ],
      'x-content-type-options': [ 'nosniff' ],
      'x-dns-prefetch-control': [ 'off' ],
      'x-download-options': [ 'noopen' ],
      'x-frame-options': [ 'SAMEORIGIN' ],
      'x-notion-request-id': [ '20554ffe-a21a-4a63-885a-9d8005e89173' ],
      'x-permitted-cross-domain-policies': [ 'none' ],
      'x-xss-protection': [ '0' ],
      'set-cookie': [
        '__cf_bm=jeD01_fAXv6OjIb5TYu9uWpLtHVsXPomIajo_TpwWO8-1730844041-1.0.1.1-DgXMHWGZxD85xkm1efcI94wh674PUlsEmbbItIdWzHGmmrSzkhSDOF9dxABw75Aev5BdtzpXngYSFqdoOAp4UA; path=/; expires=Tue, 05-Nov-24 22:30:41 GMT; domain=.notion.com; HttpOnly; Secure; SameSite=None',
        '_cfuvid=9lmJ4w1EY.0JqEqn72wGIchMqsFGOEShauhKPusIx5A-1730844041814-0.0.1.1-604800000; path=/; domain=.notion.com; HttpOnly; Secure; SameSite=None'
      ],
      server: [ 'cloudflare' ],
      'content-encoding': [ 'gzip' ]
    }
  },
  body: '{"object":"error","status":404,"code":"object_not_found","message":"Could not find block with ID: 135e58a7-7a3e-80da-b8b5-ccf48d077917. Make sure the relevant pages and databases are shared with your integration.","request_id":"20554ffe-a21a-4a63-885a-9d8005e89173"}'
}

Node.js v18.19.1

```

**Comment by kromiii** [comment]
@xzavrel Could you share the notion page which causes the error? I will duplicate it in my own workspace, and check what exactly causes the error.

**Comment by xzavrel** [comment]
Hi,
it's very simple page:

https://zavrel.notion.site/VHOD-ONLINE-135e58a77a3e80dab8b5ccf48d077917?pvs=4
https://www.notion.so/zavrel/VHOD-ONLINE-135e58a77a3e80dab8b5ccf48d077917?pvs=4

**Comment by kromiii** [comment]
hmm, I could not reproduce the issue.

```
% npm run start https://www.notion.so/khiroyuki1993/VHOD-ONLINE-13cccf416ece80b9929dc1993a18ac8c          

> @kromiii/notion-to-slides@0.1.7 start
> npm run build && node dist/index.js --url https://www.notion.so/khiroyuki1993/VHOD-ONLINE-13cccf416ece80b9929dc1993a18ac8c


> @kromiii/notion-to-slides@0.1.7 build
> tsc

pageId: 13cccf416ece80b9929dc1993a18ac8c
Example app listening at http://localhost:8080
```

I duplicated the [page](https://www.notion.so/zavrel/VHOD-ONLINE-135e58a77a3e80dab8b5ccf48d077917?pvs=4)  into my workspace, and in works well in my environment (I can see the slide below).

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/eea98f78-00f4-4093-8925-c1ff326d53a3">

**Comment by kromiii** [comment]
@xzavrel which node version do you use?

**Comment by xzavrel** [comment]
Oh, interesting, I have no idea why? Can there be some reasons like if you have side panel hidden or not etc?

I run it this way:
```
 main ✔  $ npm run start --url https://www.notion.so/zavrel/VHOD-ONLINE-135e58a77a3e80dab8b5ccf48d077917 --theme uncover

> @kromiii/notion-to-slides@0.1.7 start
> npm run build && node dist/index.js --url https://www.notion.so/zavrel/VHOD-ONLINE-135e58a77a3e80dab8b5ccf48d077917 uncover


> @kromiii/notion-to-slides@0.1.7 build
> tsc

pageId: 135e58a77a3e80dab8b5ccf48d077917
Example app listening at http://localhost:8080
```

as soon as I access to the http://localhost:8080 I get the error. Can be the error caused by some token configuration? 

I have token configured as an internal with all content capabilities. If I set wrong token I get 401 as expected.

My NPM version is 9.2.0, Node.js v18.19.1

**Comment by kromiii** [comment]
Maybe thats' true.
>  Can be the error caused by some token configuration?

In the error message you paste:
> Make sure the relevant pages and databases are shared with your integration.'

You should connect your integration token to the page you want to see.

https://developers.notion.com/docs/create-a-notion-integration#give-your-integration-page-permissions

**Comment by xzavrel** [comment]
Thank you. You are right, I didn't know I have connect the app to the specific page, and as soon I didn't get 401 I supposed it's ok.
